source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'AppBasto' do
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path

  pod 'GoogleMaps'
  pod 'react-native-maps', path: '../'
  pod 'react-native-google-maps', path: '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end
